How To Create Empty And Full Numpy Array

In [5]:
#empty array
import numpy as np 
empty_array = np.empty((3,3))
print(empty_array)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.78020169e-306 1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 0.00000000e+000]]


In [7]:
#full array 
full_array = np.full((3,3), 4)
print(full_array)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


Create Numpy Array Filled With All Zeros

In [8]:
full_array = np.full((3,3), 0)
print(full_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Create Numpy Array Filled With All Ones

In [9]:
full_array = np.full((3,3), 1)
print(full_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Check Whether Numpy Array Contain Specified Rows

In [11]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
x = np.all([1,2,3])
print(x)

[[1 2 3]
 [4 5 6]]
True


How To Remove Row In Numpy Array That Contain Non Numeric Value

In [17]:
array = np.array([[1,2,3],[4,5,6],[7,8,np.nan]])
print(array)
result = array[~np.isnan(array)]
print(result)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. nan]]
[1. 2. 3. 4. 5. 6. 7. 8.]


Remove Single Dimensional entries from shape of Array 

In [18]:
x = np.zeros((3, 1, 4))

print("Original shape: ", x.shape)

x_squeezed = np.squeeze(x)

print("New shape after squeezing: ", x_squeezed.shape)

Original shape:  (3, 1, 4)
New shape after squeezing:  (3, 4)


In [37]:
#Method 2
array = np.array([[1, 2,3], [3, 4,5], [5, 6,7]])

x = np.delete(array, 1, axis=0)

print(x) 



[[1 2 3]
 [5 6 7]]


Find Number Of Occourence Of Sequence in Numpy Array

In [56]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
output = repr(arr).count("3, 4") 
  

print(output) 

[[1 2 3]
 [4 5 6]]
0


Find Most Frequent Value in Numpy Array 

In [57]:
# create array 
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
print("Original array:") 
print(x) 
  
print("Most frequent value in the above array:") 
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


Combing One And Two Dimensional Numpy Array

In [50]:
a1 = np.array([1,2,3])
print(a1)
print('----------')
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print("Vstack")
a3 = np.vstack((a1,a2))
print(a3)


[1 2 3]
----------
[[1 2 3]
 [4 5 6]]
Vstack
[[1 2 3]
 [1 2 3]
 [4 5 6]]


How to build an array of all combination of two numpy array

In [51]:
a1 = np.array([1,2,3])
print(a1)
print('----------')
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print("Vstack")
a3 = np.vstack((a1,a2))
print(a3)

[1 2 3]
----------
[[1 2 3]
 [4 5 6]]
Vstack
[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [53]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[7,8,9],[10,11,12]])
arr4 = np.hstack((arr1,arr3))
arr4

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])